# Use the official Nginx image as a base
FROM nginx:alpine

# Copy the application files to the default Nginx directory
COPY . /usr/share/nginx/html

# Expose port 80 to allow external traffic
EXPOSE 80
